package com.takkas.modules.notification.domain.enums;

public enum NotificationType {
    APPLICATION_RECEIVED, APPLICATION_ACCEPTED, APPLICATION_REJECTED,
    SUBMISSION_SUBMITTED, SUBMISSION_APPROVED, SUBMISSION_REJECTED,
    NEW_MESSAGE, OFFER_RECEIVED, OFFER_ACCEPTED, OFFER_REJECTED,
    COUPON_ISSUED, COUPON_EXPIRING_SOON, COUPON_EXPIRED,
    SWAP_OFFER_RECEIVED, SWAP_OFFER_ACCEPTED, SWAP_OFFER_REJECTED, SWAP_OFFER_MESSAGE, SWAP_COMPLETED,
    KYC_VERIFICATION_PENDING, KYC_VERIFICATION_APPROVED, KYC_VERIFICATION_REJECTED,
    SUBSCRIPTION_RENEWED, SUBSCRIPTION_PAYMENT_FAILED, PLAN_UPGRADED, SUBSCRIPTION_UPGRADE_REQUESTED
}
